/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f103xx.h"
#include "drv_gpio.h"

void delay() {
	for (int i = 0; i < 500000/6 ; i++);
}
int main(void)
{
	GPIO_Handle_t gpioLed;
	GPIO_Handle_t gpioButton;

	(RCC->APB2ENR |= (1 << 0));
	AFIO->MAPR |= (1 << 25);

	gpioLed.pGPIO = GPIOB;
	gpioLed.pinConfig.pinMode = MODE_OUTPUT_OPENDR;
	gpioLed.pinConfig.pinSpeed = OUTPUT_SPEED_2Mhz;
	gpioLed.pinConfig.pinNumber = GPIO_PIN_4;

	gpioButton.pGPIO = GPIOA;
	gpioButton.pinConfig.pinMode = MODE_INPUT_PUPDR;
	gpioButton.pinConfig.pinNumber = GPIO_PIN_2;
	gpioButton.pinConfig.pinResType = INPUT_PULLUP;

	GPIO_PeriClockControl(GPIOA, TRUE);
	GPIO_PeriClockControl(GPIOB, TRUE);

	GPIO_Init(&gpioLed);
	GPIO_Init(&gpioButton);
	while (1) {
		if (!GPIO_ReadPin(GPIOA, GPIO_PIN_2)) {
			delay();
			GPIO_TogglePin(GPIOB, GPIO_PIN_4);
			while (!GPIO_ReadPin(GPIOA, GPIO_PIN_2)) {
				delay();
			}
		}
	}
}
